insert into cidades (codigo, nome, uf) values ('5300109','Águeda','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300110','Albergaria-a-Velha','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300111','Anadia','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300112','Arouca','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300113','Aveiro','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300114','Estarreja','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300115','Espinho','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300116','Ílhavo','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300117','Mealhada','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300118','Murtosa','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300119','Oliveira de Azeméis','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300120','Oliveira do Bairro','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300121','Ovar','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300122','Santa Maria da Feira','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300123','São João da Madeira','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300124','Sever do Vouga','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300125','Vagos','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300126','Vale de Cambra','PT-AV');
insert into cidades (codigo, nome, uf) values ('5300127','Aljustrel','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300128','Almodôvar','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300129','Alvito','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300130','Barrancos','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300131','Beja','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300132','Castro Verde','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300133','Cuba','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300134','Ferreira do Alentejo','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300135','Mértola','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300136','Moura','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300137','Odemira','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300138','Ourique','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300139','Serpa','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300140','Vidigueira','PT-BJ');
insert into cidades (codigo, nome, uf) values ('5300141','Amares','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300142','Barcelos','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300143','Braga','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300144','Cabeceiras de Basto','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300145','Celorico de Basto','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300146','Esposende','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300147','Fafe','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300148','Guimarães','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300149','Póvoa de Lanhoso','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300150','Terras de Bouro','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300151','Vieira do Minho','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300152','Vila Nova de Famalicão','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300153','Vila Verde','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300154','Vizela','PT-BR');
insert into cidades (codigo, nome, uf) values ('5300155','Alfândega da Fé','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300156','Bragança','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300157','Carrazeda de Ansiães','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300158','Freixo de Espada à Cinta','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300159','Macedo de Cavaleiros','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300160','Miranda do Douro','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300161','Mirandela','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300162','Mogadouro','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300163','Torre de Moncorvo','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300164','Vila Flor','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300165','Vimioso','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300166','Vinhais','PT-BG');
insert into cidades (codigo, nome, uf) values ('5300167','Belmonte','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300168','Castelo Branco','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300169','Covilhã','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300170','Fundão','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300171','Idanha-a-Nova','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300172','Oleiros','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300173','Penamacor','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300174','Proença-a-Nova','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300175','Sertã','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300176','Vila de Rei','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300177','Vila Velha de Ródão','PT-CB');
insert into cidades (codigo, nome, uf) values ('5300178','Arganil','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300179','Cantanhede','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300180','Coimbra','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300181','Condeixa-a-Nova','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300182','Figueira da Foz','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300183','Góis','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300184','Lousã','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300185','Mira','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300186','Miranda do Corvo','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300187','Montemor-o-Velho','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300188','Oliveira do Hospital','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300189','Pampilhosa da Serra','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300190','Penacova','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300191','Penela','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300192','Soure','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300193','Tábua','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300194','Vila Nova de Poiares','PT-CO');
insert into cidades (codigo, nome, uf) values ('5300195','Alandroal','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300196','Arraiolos','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300197','Borba','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300198','Estremoz','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300199','Évora','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300200','Montemor-o-Novo','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300201','Mora','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300202','Mourão','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300203','Portel','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300204','Redondo','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300205','Reguengos de Monsaraz','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300206','Vendas Novas','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300207','Viana do Alentejo','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300208','Vila Viçosa','PT-EV');
insert into cidades (codigo, nome, uf) values ('5300209','Albufeira','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300210','Alcoutim','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300211','Aljezur','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300212','Castro Marim','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300213','Faro','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300214','Lagoa','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300215','Lagos','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300216','Loulé','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300217','Monchique','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300218','Olhão','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300219','Portimão','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300220','São Brás de Alportel','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300221','Silves','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300222','Tavira','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300223','Vila do Bispo','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300224','Vila Real de Santo António','PT-FA');
insert into cidades (codigo, nome, uf) values ('5300225','Aguiar da Beira','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300226','Almeida','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300227','Celorico da Beira','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300228','Figueira de Castelo Rodrigo','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300229','Fornos de Algodres','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300230','Gouveia','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300231','Guarda','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300232','Manteigas','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300233','Mêda','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300234','Pinhel','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300235','Sabugal','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300236','Seia','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300237','Trancoso','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300238','Vila Nova de Foz Côa','PT-GD');
insert into cidades (codigo, nome, uf) values ('5300239','Alcobaça','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300240','Alvaiázere','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300241','Ansião','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300242','Batalha','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300243','Bombarral','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300244','Caldas da Rainha','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300245','Castanheira de Pera','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300246','Figueiró dos Vinhos','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300247','Leiria','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300248','Marinha Grande','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300249','Nazaré','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300250','Óbidos','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300251','Pedrógão Grande','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300252','Peniche','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300253','Pombal','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300254','Porto de Mós','PT-LE');
insert into cidades (codigo, nome, uf) values ('5300255','Alenquer','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300256','Amadora','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300257','Arruda dos Vinhos','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300258','Azambuja','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300259','Cadaval','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300260','Cascais','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300261','Lisboa','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300262','Loures','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300263','Lourinhã','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300264','Mafra','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300265','Odivelas','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300266','Oeiras','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300267','Sintra','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300268','Sobral de Monte Agraço','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300269','Torres Vedras','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300270','Vila Franca de Xira','PT-LI');
insert into cidades (codigo, nome, uf) values ('5300271','Alter do Chão','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300272','Arronches','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300273','Avis','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300274','Campo Maior','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300275','Castelo de Vide','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300276','Crato','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300277','Elvas','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300278','Fronteira','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300279','Gavião','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300280','Marvão','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300281','Monforte','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300282','Nisa','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300283','Ponte de Sor','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300284','Portalegre','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300285','Sousel','PT-PTG');
insert into cidades (codigo, nome, uf) values ('5300286','Amarante','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300287','Baião','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300288','Felgueiras','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300289','Gondomar','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300290','Lousada','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300291','Maia','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300292','Marco de Canaveses','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300293','Matosinhos','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300294','Paços de Ferreira','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300295','Paredes','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300296','Penafiel','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300297','Porto','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300298','Póvoa de Varzim','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300299','Santo Tirso','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300300','Trofa','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300301','Valongo','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300302','Vila do Conde','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300303','Vila Nova de Gaia','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300304','Castelo de Paiva','PT-PO');
insert into cidades (codigo, nome, uf) values ('5300305','Abrantes','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300306','Alcanena','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300307','Almeirim','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300308','Alpiarça','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300309','Benavente','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300310','Cartaxo','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300311','Chamusca','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300312','Constância','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300313','Coruche','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300314','Entroncamento','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300315','Ferreira do Zêzere','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300316','Golegã','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300317','Mação','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300318','Ourém','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300319','Rio Maior','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300320','Salvaterra de Magos','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300321','Santarém','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300322','Sardoal','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300323','Tomar','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300324','Torres Novas','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300325','Vila Nova da Barquinha','PT-SA');
insert into cidades (codigo, nome, uf) values ('5300326','Alcácer do Sal','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300327','Alcochete','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300328','Almada','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300329','Barreiro','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300330','Grândola','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300331','Moita','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300332','Montijo','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300333','Palmela','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300334','Seixal','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300335','Sesimbra','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300336','Setúbal','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300337','Sines','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300338','Santiago do Cacém','PT-SE');
insert into cidades (codigo, nome, uf) values ('5300339','Arcos de Valdevez','PT-VC');
insert into cidades (codigo, nome, uf) values ('5300340','Caminha','PT-VC');
insert into cidades (codigo, nome, uf) values ('5300341','Melgaço','PT-VC');
insert into cidades (codigo, nome, uf) values ('5300342','Monção','PT-VC');
insert into cidades (codigo, nome, uf) values ('5300343','Paredes de Coura','PT-VC');
insert into cidades (codigo, nome, uf) values ('5300344','Ponte da Barca','PT-VC');
insert into cidades (codigo, nome, uf) values ('5300345','Ponte de Lima','PT-VC');
insert into cidades (codigo, nome, uf) values ('5300346','Valença','PT-VC');
insert into cidades (codigo, nome, uf) values ('5300347','Viana do Castelo','PT-VC');
insert into cidades (codigo, nome, uf) values ('5300348','Vila Nova de Cerveira','PT-VC');
insert into cidades (codigo, nome, uf) values ('5300349','Alijó','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300350','Boticas','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300351','Chaves','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300352','Mesão Frio','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300353','Mondim de Basto','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300354','Montalegre','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300355','Murça','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300356','Peso da Régua','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300357','Ribeira de Pena','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300358','Sabrosa','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300359','Santa Marta de Penaguião','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300360','Valpaços','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300361','Vila Pouca de Aguiar','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300362','Vila Real','PT-VR');
insert into cidades (codigo, nome, uf) values ('5300363','Armamar','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300364','Carregal do Sal','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300365','Castro Daire','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300366','Cinfães','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300367','Lamego','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300368','Mangualde','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300369','Moimenta da Beira','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300370','Mortágua','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300371','Nelas','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300372','Oliveira de Frades','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300373','Penalva do Castelo','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300374','Penedono','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300375','Resende','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300376','Santa Comba Dão','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300377','São João da Pesqueira','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300378','São Pedro do Sul','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300379','Sátão','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300380','Sernancelhe','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300381','Tabuaço','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300382','Tarouca','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300383','Tondela','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300384','Vila Nova de Paiva','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300385','Viseu','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300386','Vouzela','PT-VI');
insert into cidades (codigo, nome, uf) values ('5300387','Angra do Heroísmo','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300388','Calheta (Açores)','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300389','Corvo','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300390','Horta','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300391','Lagoa (Açores)','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300392','Lajes das Flores','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300393','Lajes do Pico','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300394','Madalena','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300395','Nordeste','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300396','Ponta Delgada','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300397','Povoação','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300398','Praia da Vitória','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300399','Ribeira Grande','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300400','Santa Cruz da Graciosa','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300401','Santa Cruz das Flores','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300402','São Roque do Pico','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300403','Velas','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300404','Vila do Porto','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300405','Vila Franca do Campo','PT-AZ');
insert into cidades (codigo, nome, uf) values ('5300406','Calheta (Madeira)','PT-MA');
insert into cidades (codigo, nome, uf) values ('5300407','Câmara de Lobos','PT-MA');
insert into cidades (codigo, nome, uf) values ('5300408','Funchal','PT-MA');
insert into cidades (codigo, nome, uf) values ('5300409','Machico','PT-MA');
insert into cidades (codigo, nome, uf) values ('5300410','Ponta do Sol','PT-MA');
insert into cidades (codigo, nome, uf) values ('5300411','Porto Moniz','PT-MA');
insert into cidades (codigo, nome, uf) values ('5300412','Porto Santo','PT-MA');
insert into cidades (codigo, nome, uf) values ('5300413','Ribeira Brava','PT-MA');
insert into cidades (codigo, nome, uf) values ('5300414','Santa Cruz (Madeira)','PT-MA');
insert into cidades (codigo, nome, uf) values ('5300415','Santana','PT-MA');
insert into cidades (codigo, nome, uf) values ('5300416','São Vicente','PT-MA');