insert into cidades (codigo, nome, uf) values ('5400109','Santa Cruz de la Sierra','SC');
insert into cidades (codigo, nome, uf) values ('5400110','La Paz','LP');
insert into cidades (codigo, nome, uf) values ('5400111','Santa Cruz','SC');
insert into cidades (codigo, nome, uf) values ('5400112','El Alto','LP');
insert into cidades (codigo, nome, uf) values ('5400113','Cochabamba','CB');
insert into cidades (codigo, nome, uf) values ('5400114','Oruro','OR');
insert into cidades (codigo, nome, uf) values ('5400115','Sucre','CH');
insert into cidades (codigo, nome, uf) values ('5400116','Tarija','TJ');
insert into cidades (codigo, nome, uf) values ('5400117','Potosí','PT');
insert into cidades (codigo, nome, uf) values ('5400118','Oruro','OR');
insert into cidades (codigo, nome, uf) values ('5400119','Warnes','SC');
insert into cidades (codigo, nome, uf) values ('5400120','Sacaba','CB');
insert into cidades (codigo, nome, uf) values ('5400121','Montero','SC');
insert into cidades (codigo, nome, uf) values ('5400122','Quillacollo','CB');
insert into cidades (codigo, nome, uf) values ('5400123','Trinidad','BN');
insert into cidades (codigo, nome, uf) values ('5400124','Riberalta','BN');
insert into cidades (codigo, nome, uf) values ('5400125','Yacuiba','TJ');
insert into cidades (codigo, nome, uf) values ('5400126','Villa Tunari','CB');
insert into cidades (codigo, nome, uf) values ('5400127','Colcapirhua','CB');
insert into cidades (codigo, nome, uf) values ('5400128','Puerto Villarroel','CB');
insert into cidades (codigo, nome, uf) values ('5400129','Cobija','PD');
insert into cidades (codigo, nome, uf) values ('5400130','Sipe Sipe','CB');
insert into cidades (codigo, nome, uf) values ('5400131','Villamontes','TJ');
insert into cidades (codigo, nome, uf) values ('5400132','Guayaramerín','BN');
insert into cidades (codigo, nome, uf) values ('5400133','Camiri','SC');
insert into cidades (codigo, nome, uf) values ('5400134','Camiri','SC');
insert into cidades (codigo, nome, uf) values ('5400135','Tiquipaya','CB');
insert into cidades (codigo, nome, uf) values ('5400136','Viacha','LP');
insert into cidades (codigo, nome, uf) values ('5400137','Bermejo','TJ');
insert into cidades (codigo, nome, uf) values ('5400138','Villazón','PT');
insert into cidades (codigo, nome, uf) values ('5400139','Uyuni','PT');
insert into cidades (codigo, nome, uf) values ('5400140','Mizque','CB');
insert into cidades (codigo, nome, uf) values ('5400141','Cotoca','SC');
insert into cidades (codigo, nome, uf) values ('5400142','Yapacani','SC');
insert into cidades (codigo, nome, uf) values ('5400143','San Borja','BN');
insert into cidades (codigo, nome, uf) values ('5400144','Independencia','CB');
insert into cidades (codigo, nome, uf) values ('5400145','San Ignacio de Velasco','SC');
insert into cidades (codigo, nome, uf) values ('5400146','Tupiza','PT');
insert into cidades (codigo, nome, uf) values ('5400147','Patacamaya','LP');
insert into cidades (codigo, nome, uf) values ('5400148','Caranavi','LP');
insert into cidades (codigo, nome, uf) values ('5400149','Chimoré','CB');
insert into cidades (codigo, nome, uf) values ('5400150','San Julián','SC');
insert into cidades (codigo, nome, uf) values ('5400151','Huanuni','OR');
insert into cidades (codigo, nome, uf) values ('5400152','Llallagua','PT');
insert into cidades (codigo, nome, uf) values ('5400153','Capinota','CB');
insert into cidades (codigo, nome, uf) values ('5400154','Rurrenabaque','BN');
insert into cidades (codigo, nome, uf) values ('5400155','Ascención de Guarayos','SC');
insert into cidades (codigo, nome, uf) values ('5400156','Achocalla','LP');
insert into cidades (codigo, nome, uf) values ('5400157','Mineros','SC');
insert into cidades (codigo, nome, uf) values ('5400158','San José de Chiquitos','SC');
insert into cidades (codigo, nome, uf) values ('5400159','Vallegrande','SC');
insert into cidades (codigo, nome, uf) values ('5400160','Mapiri','LP');
insert into cidades (codigo, nome, uf) values ('5400161','Portachuelo','SC');
insert into cidades (codigo, nome, uf) values ('5400162','Comarapa','SC');
insert into cidades (codigo, nome, uf) values ('5400163','Punata','CB');
insert into cidades (codigo, nome, uf) values ('5400164','Villa Yapacaní','SC');
insert into cidades (codigo, nome, uf) values ('5400165','Ascensión','SC');
insert into cidades (codigo, nome, uf) values ('5400166','Vinto','CB');
insert into cidades (codigo, nome, uf) values ('5400167','Chulumani','LP');
insert into cidades (codigo, nome, uf) values ('5400168','Santa Ana de Yacuma','BN');
insert into cidades (codigo, nome, uf) values ('5400169','Challapata','OR');
insert into cidades (codigo, nome, uf) values ('5400170','Okinawa Número Uno','SC');
insert into cidades (codigo, nome, uf) values ('5400171','Puerto Suárez','SC');
insert into cidades (codigo, nome, uf) values ('5400172','Corocoro','LP');
insert into cidades (codigo, nome, uf) values ('5400173','Torotoro','PT');
insert into cidades (codigo, nome, uf) values ('5400174','Puerto Quijarro','SC');
insert into cidades (codigo, nome, uf) values ('5400175','Roboré','SC');
insert into cidades (codigo, nome, uf) values ('5400176','San Ignacio de Moxo','BN');
insert into cidades (codigo, nome, uf) values ('5400177','Pailón','SC');
insert into cidades (codigo, nome, uf) values ('5400178','Achacachi','LP');
insert into cidades (codigo, nome, uf) values ('5400179','Reyes','BN');
insert into cidades (codigo, nome, uf) values ('5400180','Monteagudo','CH');
insert into cidades (codigo, nome, uf) values ('5400181','Aiquile','CB');
insert into cidades (codigo, nome, uf) values ('5400182','Charagua','SC');
insert into cidades (codigo, nome, uf) values ('5400183','Cliza','CB');
insert into cidades (codigo, nome, uf) values ('5400184','Ivirgarzama','CB');
insert into cidades (codigo, nome, uf) values ('5400185','San Carlos','SC');
insert into cidades (codigo, nome, uf) values ('5400186','Copacabana','LP');
insert into cidades (codigo, nome, uf) values ('5400187','Lahuachaca','LP');
insert into cidades (codigo, nome, uf) values ('5400188','Uncia','PT');
insert into cidades (codigo, nome, uf) values ('5400189','San Ramón','BN');
insert into cidades (codigo, nome, uf) values ('5400190','Santiago de Machaca','LP');
insert into cidades (codigo, nome, uf) values ('5400191','San Joaquín','BN');
insert into cidades (codigo, nome, uf) values ('5400192','Camargo','CH');
insert into cidades (codigo, nome, uf) values ('5400193','Samaipata','SC');
insert into cidades (codigo, nome, uf) values ('5400194','Magdalena','BN');
insert into cidades (codigo, nome, uf) values ('5400195','Santa Rosa del Sara','SC');
insert into cidades (codigo, nome, uf) values ('5400196','Colquiri','LP');
insert into cidades (codigo, nome, uf) values ('5400197','Guanay','LP');
insert into cidades (codigo, nome, uf) values ('5400198','Mairana','SC');
insert into cidades (codigo, nome, uf) values ('5400199','Sicasica','LP');
insert into cidades (codigo, nome, uf) values ('5400200','Buena Vista','SC');
insert into cidades (codigo, nome, uf) values ('5400201','Colomi','CB');
insert into cidades (codigo, nome, uf) values ('5400202','Padilla','CH');
insert into cidades (codigo, nome, uf) values ('5400203','Arani','CB');
insert into cidades (codigo, nome, uf) values ('5400204','Tarata','CB');
insert into cidades (codigo, nome, uf) values ('5400205','Puerto Pailas','SC');
insert into cidades (codigo, nome, uf) values ('5400206','Limoncito','SC');
insert into cidades (codigo, nome, uf) values ('5400207','Huacaraje','BN');
insert into cidades (codigo, nome, uf) values ('5400208','Villa Serrano','CH');
insert into cidades (codigo, nome, uf) values ('5400209','Puerto Rico','PD');
insert into cidades (codigo, nome, uf) values ('5400210','Irpa Irpa','CB');
insert into cidades (codigo, nome, uf) values ('5400211','Santa Bárbara','PT');