-- All countries
-- https://www.html-code-generator.com/mysql/country-name-table

INSERT INTO `paises` (`id`, `codigo`, `nome`) VALUES
(1, 'AF', 'Afeganistão'),
(2, 'AX', 'Ilhas Aland'),
(3, 'AL', 'Albânia'),
(4, 'DZ', 'Argélia'),
(5, 'AS', 'Samoa Americana'),
(6, 'AD', 'Andorra'),
(7, 'AO', 'Angola'),
(8, 'AI', 'Anguila'),
(9, 'AQ', 'Antártida'),
(10, 'AG', 'Antígua e Barbuda'),
(11, 'AR', 'Argentina'),
(12, 'AM', 'Armênia'),
(13, 'AW', 'Aruba'),
(14, 'AU', 'Austrália'),
(15, 'AT', 'Áustria'),
(16, 'AZ', 'Azerbaijão'),
(17, 'BS', 'Bahamas'),
(18, 'BH', 'Barein'),
(19, 'BD', 'Bangladesh'),
(20, 'BB', 'Barbados'),
(21, 'BY', 'Bielorrússia'),
(22, 'BE', 'Bélgica'),
(23, 'BZ', 'Belize'),
(24, 'BJ', 'Benin'),
(25, 'BM', 'Bermudas'),
(26, 'BT', 'Butão'),
(27, 'BO', 'Bolívia'),
(28, 'BA', 'Bósnia e Herzegovina'),
(29, 'BW', 'Botsuana'),
(30, 'BV', 'Ilha Bouvet'),
(31, 'BR', 'Brasil'),
(32, 'IO', 'Território Britânico do Oceano Índico'),
(33, 'BN', 'Brunei'),
(34, 'BG', 'Bulgária'),
(35, 'BF', 'Burquina Faso'),
(36, 'BI', 'Burundi'),
(37, 'CV', 'Cabo Verde'),
(38, 'KH', 'Camboja'),
(39, 'CM', 'Camarões'),
(40, 'CA', 'Canadá'),
(41, 'BQ', 'Países Baixos Caribenhos'),
(42, 'KY', 'Ilhas Cayman'),
(43, 'CF', 'República Centro-Africana'),
(44, 'TD', 'Chade'),
(45, 'CL', 'Chile'),
(46, 'CN', 'China'),
(47, 'CX', 'Ilha Christmas'),
(48, 'CC', 'Ilhas Cocos (Keeling)'),
(49, 'CO', 'Colômbia'),
(50, 'KM', 'Comores'),
(51, 'CG', 'República do Congo'),
(52, 'CD', 'Congo - Kinshasa'),
(53, 'CK', 'Ilhas Cook'),
(54, 'CR', 'Costa Rica'),
(55, 'HR', 'Croácia'),
(56, 'CU', 'Cuba'),
(57, 'CW', 'Curaçao'),
(58, 'CY', 'Chipre'),
(59, 'CZ', 'Tchéquia'),
(60, 'CI', 'Costa do Marfim'),
(61, 'DK', 'Dinamarca'),
(62, 'DJ', 'Djibuti'),
(63, 'DM', 'Dominica'),
(64, 'DO', 'República Dominicana'),
(65, 'EC', 'Equador'),
(66, 'EG', 'Egito'),
(67, 'SV', 'El Salvador'),
(68, 'GQ', 'Guiné Equatorial'),
(69, 'ER', 'Eritreia'),
(70, 'EE', 'Estônia'),
(71, 'SZ', 'Essuatíni'),
(72, 'ET', 'Etiópia'),
(73, 'FK', 'Ilhas Malvinas'),
(74, 'FO', 'Ilhas Faroé'),
(75, 'FJ', 'Fiji'),
(76, 'FI', 'Finlândia'),
(77, 'FR', 'França'),
(78, 'GF', 'Guiana Francesa'),
(79, 'PF', 'Polinésia Francesa'),
(80, 'TF', 'Territórios Franceses do Sul'),
(81, 'GA', 'Gabão'),
(82, 'GM', 'Gâmbia'),
(83, 'GE', 'Geórgia'),
(84, 'DE', 'Alemanha'),
(85, 'GH', 'Gana'),
(86, 'GI', 'Gibraltar'),
(87, 'GR', 'Grécia'),
(88, 'GL', 'Groenlândia'),
(89, 'GD', 'Granada'),
(90, 'GP', 'Guadalupe'),
(91, 'GU', 'Guam'),
(92, 'GT', 'Guatemala'),
(93, 'GG', 'Guernsey'),
(94, 'GN', 'Guiné'),
(95, 'GW', 'Guiné-Bissau'),
(96, 'GY', 'Guiana'),
(97, 'HT', 'Haiti'),
(98, 'HM', 'Ilhas Heard e McDonald'),
(99, 'HN', 'Honduras'),
(100, 'HK', 'Hong Kong, RAE da China'),
(101, 'HU', 'Hungria'),
(102, 'IS', 'Islândia'),
(103, 'IN', 'Índia'),
(104, 'ID', 'Indonésia'),
(105, 'IR', 'Irã'),
(106, 'IQ', 'Iraque'),
(107, 'IE', 'Irlanda'),
(108, 'IM', 'Ilha de Man'),
(109, 'IL', 'Israel'),
(110, 'IT', 'Itália'),
(111, 'JM', 'Jamaica'),
(112, 'JP', 'Japão'),
(113, 'JE', 'Jersey'),
(114, 'JO', 'Jordânia'),
(115, 'KZ', 'Cazaquistão'),
(116, 'KE', 'Quênia'),
(117, 'KI', 'Quiribati'),
(118, 'KP', 'Coreia do Norte'),
(119, 'KR', 'Coreia do Sul'),
(120, 'XK', 'Kosovo'),
(121, 'KW', 'Kuwait'),
(122, 'KG', 'Quirguistão'),
(123, 'LA', 'Laos'),
(124, 'LV', 'Letônia'),
(125, 'LB', 'Líbano'),
(126, 'LS', 'Lesoto'),
(127, 'LR', 'Libéria'),
(128, 'LY', 'Líbia'),
(129, 'LI', 'Liechtenstein'),
(130, 'LT', 'Lituânia'),
(131, 'LU', 'Luxemburgo'),
(132, 'MO', 'Macau, RAE da China'),
(133, 'MK', 'Macedônia do Norte'),
(134, 'MG', 'Madagascar'),
(135, 'MW', 'Malaui'),
(136, 'MY', 'Malásia'),
(137, 'MV', 'Maldivas'),
(138, 'ML', 'Mali'),
(139, 'MT', 'Malta'),
(140, 'MH', 'Ilhas Marshall'),
(141, 'MQ', 'Martinica'),
(142, 'MR', 'Mauritânia'),
(143, 'MU', 'Maurício'),
(144, 'YT', 'Mayotte'),
(145, 'MX', 'México'),
(146, 'FM', 'Micronésia'),
(147, 'MD', 'Moldávia'),
(148, 'MC', 'Mônaco'),
(149, 'MN', 'Mongólia'),
(150, 'ME', 'Montenegro'),
(151, 'MS', 'Montserrat'),
(152, 'MA', 'Marrocos'),
(153, 'MZ', 'Moçambique'),
(154, 'MM', 'Mianmar (Birmânia)'),
(155, 'NA', 'Namíbia'),
(156, 'NR', 'Nauru'),
(157, 'NP', 'Nepal'),
(158, 'NL', 'Países Baixos'),
(159, 'AN', 'Curaçao'),
(160, 'NC', 'Nova Caledônia'),
(161, 'NZ', 'Nova Zelândia'),
(162, 'NI', 'Nicarágua'),
(163, 'NE', 'Níger'),
(164, 'NG', 'Nigéria'),
(165, 'NU', 'Niue'),
(166, 'NF', 'Ilha Norfolk'),
(167, 'MP', 'Ilhas Marianas do Norte'),
(168, 'NO', 'Noruega'),
(169, 'OM', 'Omã'),
(170, 'PK', 'Paquistão'),
(171, 'PW', 'Palau'),
(172, 'PS', 'Territórios palestinos'),
(173, 'PA', 'Panamá'),
(174, 'PG', 'Papua-Nova Guiné'),
(175, 'PY', 'Paraguai'),
(176, 'PE', 'Peru'),
(177, 'PH', 'Filipinas'),
(178, 'PN', 'Ilhas Pitcairn'),
(179, 'PL', 'Polônia'),
(180, 'PT', 'Portugal'),
(181, 'PR', 'Porto Rico'),
(182, 'QA', 'Catar'),
(183, 'RE', 'Reunião'),
(184, 'RO', 'Romênia'),
(185, 'RU', 'Rússia'),
(186, 'RW', 'Ruanda'),
(187, 'BL', 'São Bartolomeu'),
(188, 'SH', 'Santa Helena'),
(189, 'KN', 'São Cristóvão e Névis'),
(190, 'LC', 'Santa Lúcia'),
(191, 'MF', 'São Martinho'),
(192, 'PM', 'São Pedro e Miquelão'),
(193, 'VC', 'São Vicente e Granadinas'),
(194, 'WS', 'Samoa'),
(195, 'SM', 'San Marino'),
(196, 'ST', 'São Tomé e Príncipe'),
(197, 'SA', 'Arábia Saudita'),
(198, 'SN', 'Senegal'),
(199, 'RS', 'Sérvia'),
(200, 'CS', 'Sérvia'),
(201, 'SC', 'Seicheles'),
(202, 'SL', 'Serra Leoa'),
(203, 'SG', 'Singapura'),
(204, 'SX', 'Sint Maarten'),
(205, 'SK', 'Eslováquia'),
(206, 'SI', 'Eslovênia'),
(207, 'SB', 'Ilhas Salomão'),
(208, 'SO', 'Somália'),
(209, 'ZA', 'África do Sul'),
(210, 'GS', 'Ilhas Geórgia do Sul e Sandwich do Sul'),
(211, 'SS', 'Sudão do Sul'),
(212, 'ES', 'Espanha'),
(213, 'LK', 'Sri Lanka'),
(214, 'SD', 'Sudão'),
(215, 'SR', 'Suriname'),
(216, 'SJ', 'Svalbard e Jan Mayen'),
(217, 'SE', 'Suécia'),
(218, 'CH', 'Suíça'),
(219, 'SY', 'Síria'),
(220, 'TW', 'Taiwan'),
(221, 'TJ', 'Tadjiquistão'),
(222, 'TZ', 'Tanzânia'),
(223, 'TH', 'Tailândia'),
(224, 'TL', 'Timor-Leste'),
(225, 'TG', 'Togo'),
(226, 'TK', 'Tokelau'),
(227, 'TO', 'Tonga'),
(228, 'TT', 'Trinidad e Tobago'),
(229, 'TN', 'Tunísia'),
(230, 'TR', 'Turquia'),
(231, 'TM', 'Turcomenistão'),
(232, 'TC', 'Ilhas Turcas e Caicos'),
(233, 'TV', 'Tuvalu'),
(234, 'UM', 'Ilhas Menores Distantes dos EUA'),
(235, 'UG', 'Uganda'),
(236, 'UA', 'Ucrânia'),
(237, 'AE', 'Emirados Árabes Unidos'),
(238, 'GB', 'Reino Unido'),
(239, 'US', 'Estados Unidos'),
(240, 'UY', 'Uruguai'),
(241, 'UZ', 'Uzbequistão'),
(242, 'VU', 'Vanuatu'),
(243, 'VA', 'Cidade do Vaticano'),
(244, 'VE', 'Venezuela'),
(245, 'VN', 'Vietnã'),
(246, 'VG', 'Ilhas Virgens Britânicas'),
(247, 'VI', 'Ilhas Virgens Americanas'),
(248, 'WF', 'Wallis e Futuna'),
(249, 'EH', 'Saara Ocidental'),
(250, 'YE', 'Iêmen'),
(251, 'ZM', 'Zâmbia'),
(252, 'ZW', 'Zimbábue');